### ISSUE TITLE
PHPMyAdmin not accessible after installation 

### ISSUE THREAD

**Issue by llevvi** [emilas44/laravel-5.2-on-Ubuntu#1]
> //install phpmyadmin
sudo apt-get install phpmyadmin 	
		# later accessible through localhost/phpmyadmin

I followed the instructions but I still get:

_Not Found_

_The requested URL /phpmyadmin was not found on this server_

**Comment by emilas44** [comment]
Hi, did you watch my whole video on youtube???
https://www.youtube.com/watch?v=A6TdaRIsG6g

 How did you found my email address? :)

On Thu, May 19, 2016 at 8:52 PM, Leandro Vicente Silva <
notifications@github.com> wrote:

> //install phpmyadmin
> sudo apt-get install phpmyadmin
>
> # later accessible through localhost/phpmyadmin
>
> I followed the instructions but I still get:
>
> *Not Found*
>
> *The requested URL /localhost was not found on this server*
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emilas44/laravel-5.2-on-Ubuntu/issues/1>
>



-- 
Elvis Milas bacc.ing.techn.inf.

**Comment by llevvi** [comment]
Yes, I watched and followed the whole video.
I don't have your email address. I just added an issue on your Github repo.

**Comment by emilas44** [comment]
i think you skipped the part where you need to select for phpmyadmin to use apache server....maybe?
at 3:19

**Comment by llevvi** [comment]
I finally found a solution after this long period! (I've given up from using phpmyadmin and I was doing everything using MySQL Workbench instead.

Here it follows:

> If you get a 404 error upon visiting http://localhost/phpmyadmin: You will need to configure apache2.conf to work with Phpmyadmin.
> 
> $ gksudo gedit /etc/apache2/apache2.conf
> 
> Include the following line at the bottom of the file, save and quit.
> 
> $ Include /etc/phpmyadmin/apache.conf

Source: http://askubuntu.com/questions/55280/phpmyadmin-is-not-working-after-i-installed-it
